
new_studyareas: ['BrackishWater',
                  'AprilReports_Misc']
studyareas: ['SanJuanBasin',
              'RioArribaCounty',
              'AcomaBasin',
              'RioSanJoseBasin',
              'SanAgustinPlains',
              'GilaSanFrancisco',
              'MimbresBasin',
              'BootheelBasinAndRange',
              'RatonBasin',
              'UnionCounty',
              'EstanciaBasin',
              'HighPlains',
              'SacramentoMountainsPecosSlope',
              'RoswellArtesianBasin',
              'DelawareBasin',
              'CapitanReefAquifer',
              'SaltBasin',
              'SanLuisBasin',
              'EspanolaBasin',
              'SantoDomingoBasin',
              'AlbuquerqueBasin',
              'SocorroBasin',
              'LaJenciaBasin',
              'SanMarcialBasin',
              'EngleBasin',
              'PalomasBasin',
              'JornadaDelMuertoBasin',
              'TularosaBasin',
              'MesillaBasin',
              'MISC_AREAS']

questions_file: ''